DELIMITER $$

USE `db_aem`$$

DROP PROCEDURE IF EXISTS `RSP_CLIENTES`$$

CREATE
    /*[DEFINER = { user | CURRENT_USER }]*/
    PROCEDURE `db_aem`.`RSP_CLIENTES_PERSONALIZADO`(IN _TEXTO_NOME VARCHAR(80), _TEXTO_APELIDO VARCHAR(80))
    BEGIN
    	SELECT COD_CLI, NOME_CLI, CPFCGC_CLI, EMAIL_CLI, SEXO, APELIDO_CLI, DT_NASC_CLI, INSCRICAO_EST
	  FROM CLIENTES
	 WHERE (_TEXTO_NOME = '' OR NOME_CLI LIKE _TEXTO_NOME)
	   AND (_TEXTO_APELIDO = '' OR APELIDO_CLI LIKE _TEXTO_APELIDO);
    END$$

DELIMITER ;